// Generated by scripts/sync-profiles.mjs. Do not edit.
#pragma once
#if CONFIG_IDF_TARGET_ESP32
static const char* FL_FAMILY="esp32";
static const int FL_GPIO[]={4,13,14,16,17,18,19,21,22,23,25,26,27,32,33,34,35,36,39};
static const int FL_ADC[]={32,33,34,35,36,39};
#elif CONFIG_IDF_TARGET_ESP32S2
static const char* FL_FAMILY="esp32s2";
static const int FL_GPIO[]={1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21};
static const int FL_ADC[]={1,2,3,4,5,6,7,8,9,10};
#elif CONFIG_IDF_TARGET_ESP32S3
static const char* FL_FAMILY="esp32s3";
static const int FL_GPIO[]={1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,21};
static const int FL_ADC[]={1,2,4,5,6,7,8,9,10};
#elif CONFIG_IDF_TARGET_ESP32C3
static const char* FL_FAMILY="esp32c3";
static const int FL_GPIO[]={0,1,3,4,5,6,7,10};
static const int FL_ADC[]={0,1,3,4};
#elif CONFIG_IDF_TARGET_ESP32C6
static const char* FL_FAMILY="esp32c6";
static const int FL_GPIO[]={0,1,2,3,4,5,6,7,10,11,18,19,20,21,22,23};
static const int FL_ADC[]={0,1,2,3,4,5,6};
#else
#error "FlowLabBridge: unsupported SoC profile. Add a verified profile first."
#endif
